swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      tags:
        - User's transaction Module
      summary: Transactions
      description: API for User's transactions
      parameters:
        - in: body
          name: body
          description: transactions Payload
          required: true
          schema:
            $ref: '#/definitions/transactions'
      produces:
        - application/json
      responses:
        '200':
          description: transaction loaded Successfully
          schema:
            $ref: '#/definitions/transactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error


  /user/Transaction:
    put:
      security:
        - Bearer: []
      tags:
        - User's transaction Module
      summary: User transaction API
      description: API for updating a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user's transaction attributes
          required: true
          schema:
            $ref: '#/definitions/UserTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      transactionDate:
        type: string
        description: user transaction date
      transactionDescription:
        type: string
        description: user transaction description
      transactionAmount:
        type: string
        description: user transaction amount
      Balance:
        type: string
        description: user account Balance
       
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string


  UserTransaction:
    type: object
    properties:
    transactionDate:
        type: string
        description: user transaction date
      transactionDescription:
        type: string
        description: user transaction description
      transactionAmount:
        type: string
        description: user transaction amount
      Balance:
        type: string
        description: user account Balance
      category:
        type: string
        description: user transaction category
      note:
        type: string
        description: user transaction note

