swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      tags:
        - User Module
      summary: Get a list of all user's transactions
      description: This endpoint is used to retrieve all user's transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: transaction retrieved Successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/UserTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update a user transactions (category/notes)
      description: Update an existing user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user's transaction attributes
          required: true
          schema:
            type: object
            items:
            $ref: '#/definitions/TransactionDescription
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  UserTransactions:
    type: object
    properties:
      id:
        type: string
      transactionDate:
        type: string
        description: user transaction date
      transactionDescription:
        type: string
        description: user transaction description
      transactionAmount:
        type: string
        description: user transaction amount
      accountBalance:
        type: string
        description: user account Balance
      transactionType:
        type: string
        description: user transaction type  
      transactionCategory:
        type: string
        description: user transaction category  
      transactionNotes:
        type: string
        description: user transaction notes 

  TransactionDescription:
    type: object
    properties:
      transactionCategory:
        type: string
      transactionNotes:
        type: string

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

